//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MovilBusiness.Droid.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosSoap", Namespace="http://tempuri.org/")]
    public partial class Servicios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback PedidosCrearOperationCompleted;
        
        private System.Threading.SendOrPostCallback PedidosCrear2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SuscriptoresCrearOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarSuscriptorOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuscriptoresCambiosCantidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReplicacionesTablasLeerOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuscriptoresCambiosLeerOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuscriptoresCambiosLeerImagenesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuscriptoresCambiosLeer2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerArchivosCambiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback execQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback execQuery2OperationCompleted;
        
        private System.Threading.SendOrPostCallback execQueryResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback execQueryInsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback PresupuestosCombosJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveBackupOperationCompleted;
        
        private System.Threading.SendOrPostCallback PresupuestosCargarOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecQueryWithResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback RepresentantesParametrosActualizarOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarEmpresaSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback VersionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servicios() {
            this.Url = "http://movilbusiness.com.do/wsMovilbusiness1076/Servicios.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetVersionCompletedEventHandler GetVersionCompleted;
        
        /// <remarks/>
        public event PedidosCrearCompletedEventHandler PedidosCrearCompleted;
        
        /// <remarks/>
        public event PedidosCrear2CompletedEventHandler PedidosCrear2Completed;
        
        /// <remarks/>
        public event SuscriptoresCrearCompletedEventHandler SuscriptoresCrearCompleted;
        
        /// <remarks/>
        public event VerificarSuscriptorCompletedEventHandler VerificarSuscriptorCompleted;
        
        /// <remarks/>
        public event SuscriptoresCambiosCantidadCompletedEventHandler SuscriptoresCambiosCantidadCompleted;
        
        /// <remarks/>
        public event ReplicacionesTablasLeerCompletedEventHandler ReplicacionesTablasLeerCompleted;
        
        /// <remarks/>
        public event SuscriptoresCambiosLeerCompletedEventHandler SuscriptoresCambiosLeerCompleted;
        
        /// <remarks/>
        public event SuscriptoresCambiosLeerImagenesCompletedEventHandler SuscriptoresCambiosLeerImagenesCompleted;
        
        /// <remarks/>
        public event SuscriptoresCambiosLeer2CompletedEventHandler SuscriptoresCambiosLeer2Completed;
        
        /// <remarks/>
        public event ObtenerArchivosCambiosCompletedEventHandler ObtenerArchivosCambiosCompleted;
        
        /// <remarks/>
        public event execQueryCompletedEventHandler execQueryCompleted;
        
        /// <remarks/>
        public event execQuery2CompletedEventHandler execQuery2Completed;
        
        /// <remarks/>
        public event execQueryResultCompletedEventHandler execQueryResultCompleted;
        
        /// <remarks/>
        public event execQueryInsertCompletedEventHandler execQueryInsertCompleted;
        
        /// <remarks/>
        public event ExecuteQueryCompletedEventHandler ExecuteQueryCompleted;
        
        /// <remarks/>
        public event PresupuestosCombosJSONCompletedEventHandler PresupuestosCombosJSONCompleted;
        
        /// <remarks/>
        public event SaveBackupCompletedEventHandler SaveBackupCompleted;
        
        /// <remarks/>
        public event PresupuestosCargarOnlineCompletedEventHandler PresupuestosCargarOnlineCompleted;
        
        /// <remarks/>
        public event ExecQueryWithResultCompletedEventHandler ExecQueryWithResultCompleted;
        
        /// <remarks/>
        public event RepresentantesParametrosActualizarCompletedEventHandler RepresentantesParametrosActualizarCompleted;
        
        /// <remarks/>
        public event CargarEmpresaSyncCompletedEventHandler CargarEmpresaSyncCompleted;
        
        /// <remarks/>
        public event VersionCompletedEventHandler VersionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetVersion() {
            object[] results = this.Invoke("GetVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetVersionAsync() {
            this.GetVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetVersionAsync(object userState) {
            if ((this.GetVersionOperationCompleted == null)) {
                this.GetVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVersionOperationCompleted);
            }
            this.InvokeAsync("GetVersion", new object[0], this.GetVersionOperationCompleted, userState);
        }
        
        private void OnGetVersionOperationCompleted(object arg) {
            if ((this.GetVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVersionCompleted(this, new GetVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PedidosCrear", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PedidosCrear(string CliCodigo, string RepCodigo, string RepClave, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] _PedDetalle[] detalle21) {
            object[] results = this.Invoke("PedidosCrear", new object[] {
                        CliCodigo,
                        RepCodigo,
                        RepClave,
                        detalle21});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PedidosCrearAsync(string CliCodigo, string RepCodigo, string RepClave, _PedDetalle[] detalle21) {
            this.PedidosCrearAsync(CliCodigo, RepCodigo, RepClave, detalle21, null);
        }
        
        /// <remarks/>
        public void PedidosCrearAsync(string CliCodigo, string RepCodigo, string RepClave, _PedDetalle[] detalle21, object userState) {
            if ((this.PedidosCrearOperationCompleted == null)) {
                this.PedidosCrearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPedidosCrearOperationCompleted);
            }
            this.InvokeAsync("PedidosCrear", new object[] {
                        CliCodigo,
                        RepCodigo,
                        RepClave,
                        detalle21}, this.PedidosCrearOperationCompleted, userState);
        }
        
        private void OnPedidosCrearOperationCompleted(object arg) {
            if ((this.PedidosCrearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PedidosCrearCompleted(this, new PedidosCrearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PedidosCrear2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PedidosCrear2(string CliCodigo, string RepCodigo, string RepClave, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] _PedDetalle[] detalle21) {
            object[] results = this.Invoke("PedidosCrear2", new object[] {
                        CliCodigo,
                        RepCodigo,
                        RepClave,
                        detalle21});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PedidosCrear2Async(string CliCodigo, string RepCodigo, string RepClave, _PedDetalle[] detalle21) {
            this.PedidosCrear2Async(CliCodigo, RepCodigo, RepClave, detalle21, null);
        }
        
        /// <remarks/>
        public void PedidosCrear2Async(string CliCodigo, string RepCodigo, string RepClave, _PedDetalle[] detalle21, object userState) {
            if ((this.PedidosCrear2OperationCompleted == null)) {
                this.PedidosCrear2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnPedidosCrear2OperationCompleted);
            }
            this.InvokeAsync("PedidosCrear2", new object[] {
                        CliCodigo,
                        RepCodigo,
                        RepClave,
                        detalle21}, this.PedidosCrear2OperationCompleted, userState);
        }
        
        private void OnPedidosCrear2OperationCompleted(object arg) {
            if ((this.PedidosCrear2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PedidosCrear2Completed(this, new PedidosCrear2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuscriptoresCrear", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SuscriptoresCrear(string RepCodigo, string RepClave, string RepNombre) {
            object[] results = this.Invoke("SuscriptoresCrear", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SuscriptoresCrearAsync(string RepCodigo, string RepClave, string RepNombre) {
            this.SuscriptoresCrearAsync(RepCodigo, RepClave, RepNombre, null);
        }
        
        /// <remarks/>
        public void SuscriptoresCrearAsync(string RepCodigo, string RepClave, string RepNombre, object userState) {
            if ((this.SuscriptoresCrearOperationCompleted == null)) {
                this.SuscriptoresCrearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuscriptoresCrearOperationCompleted);
            }
            this.InvokeAsync("SuscriptoresCrear", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre}, this.SuscriptoresCrearOperationCompleted, userState);
        }
        
        private void OnSuscriptoresCrearOperationCompleted(object arg) {
            if ((this.SuscriptoresCrearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuscriptoresCrearCompleted(this, new SuscriptoresCrearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarSuscriptor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerificarSuscriptor(string UsuInicioSesion, string UsuClave, string RepSuscriptor) {
            object[] results = this.Invoke("VerificarSuscriptor", new object[] {
                        UsuInicioSesion,
                        UsuClave,
                        RepSuscriptor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarSuscriptorAsync(string UsuInicioSesion, string UsuClave, string RepSuscriptor) {
            this.VerificarSuscriptorAsync(UsuInicioSesion, UsuClave, RepSuscriptor, null);
        }
        
        /// <remarks/>
        public void VerificarSuscriptorAsync(string UsuInicioSesion, string UsuClave, string RepSuscriptor, object userState) {
            if ((this.VerificarSuscriptorOperationCompleted == null)) {
                this.VerificarSuscriptorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarSuscriptorOperationCompleted);
            }
            this.InvokeAsync("VerificarSuscriptor", new object[] {
                        UsuInicioSesion,
                        UsuClave,
                        RepSuscriptor}, this.VerificarSuscriptorOperationCompleted, userState);
        }
        
        private void OnVerificarSuscriptorOperationCompleted(object arg) {
            if ((this.VerificarSuscriptorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarSuscriptorCompleted(this, new VerificarSuscriptorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuscriptoresCambiosCantidad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SuscriptoresCambiosCantidad(string RepCodigo, string RepClave, string RepSuscriptor) {
            object[] results = this.Invoke("SuscriptoresCambiosCantidad", new object[] {
                        RepCodigo,
                        RepClave,
                        RepSuscriptor});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SuscriptoresCambiosCantidadAsync(string RepCodigo, string RepClave, string RepSuscriptor) {
            this.SuscriptoresCambiosCantidadAsync(RepCodigo, RepClave, RepSuscriptor, null);
        }
        
        /// <remarks/>
        public void SuscriptoresCambiosCantidadAsync(string RepCodigo, string RepClave, string RepSuscriptor, object userState) {
            if ((this.SuscriptoresCambiosCantidadOperationCompleted == null)) {
                this.SuscriptoresCambiosCantidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuscriptoresCambiosCantidadOperationCompleted);
            }
            this.InvokeAsync("SuscriptoresCambiosCantidad", new object[] {
                        RepCodigo,
                        RepClave,
                        RepSuscriptor}, this.SuscriptoresCambiosCantidadOperationCompleted, userState);
        }
        
        private void OnSuscriptoresCambiosCantidadOperationCompleted(object arg) {
            if ((this.SuscriptoresCambiosCantidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuscriptoresCambiosCantidadCompleted(this, new SuscriptoresCambiosCantidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReplicacionesTablasLeer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReplicacionesTablasLeer(string RepCodigo, string RepClave, string RepNombre) {
            object[] results = this.Invoke("ReplicacionesTablasLeer", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReplicacionesTablasLeerAsync(string RepCodigo, string RepClave, string RepNombre) {
            this.ReplicacionesTablasLeerAsync(RepCodigo, RepClave, RepNombre, null);
        }
        
        /// <remarks/>
        public void ReplicacionesTablasLeerAsync(string RepCodigo, string RepClave, string RepNombre, object userState) {
            if ((this.ReplicacionesTablasLeerOperationCompleted == null)) {
                this.ReplicacionesTablasLeerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReplicacionesTablasLeerOperationCompleted);
            }
            this.InvokeAsync("ReplicacionesTablasLeer", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre}, this.ReplicacionesTablasLeerOperationCompleted, userState);
        }
        
        private void OnReplicacionesTablasLeerOperationCompleted(object arg) {
            if ((this.ReplicacionesTablasLeerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReplicacionesTablasLeerCompleted(this, new ReplicacionesTablasLeerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuscriptoresCambiosLeer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SuscriptoresCambiosLeer(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor, int RepCantidad) {
            object[] results = this.Invoke("SuscriptoresCambiosLeer", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre,
                        RepSuscriptor,
                        RepCantidad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SuscriptoresCambiosLeerAsync(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor, int RepCantidad) {
            this.SuscriptoresCambiosLeerAsync(RepCodigo, RepClave, RepNombre, RepSuscriptor, RepCantidad, null);
        }
        
        /// <remarks/>
        public void SuscriptoresCambiosLeerAsync(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor, int RepCantidad, object userState) {
            if ((this.SuscriptoresCambiosLeerOperationCompleted == null)) {
                this.SuscriptoresCambiosLeerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuscriptoresCambiosLeerOperationCompleted);
            }
            this.InvokeAsync("SuscriptoresCambiosLeer", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre,
                        RepSuscriptor,
                        RepCantidad}, this.SuscriptoresCambiosLeerOperationCompleted, userState);
        }
        
        private void OnSuscriptoresCambiosLeerOperationCompleted(object arg) {
            if ((this.SuscriptoresCambiosLeerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuscriptoresCambiosLeerCompleted(this, new SuscriptoresCambiosLeerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuscriptoresCambiosLeerImagenes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SuscriptoresCambiosLeerImagenes(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor, int RepCantidad) {
            object[] results = this.Invoke("SuscriptoresCambiosLeerImagenes", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre,
                        RepSuscriptor,
                        RepCantidad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SuscriptoresCambiosLeerImagenesAsync(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor, int RepCantidad) {
            this.SuscriptoresCambiosLeerImagenesAsync(RepCodigo, RepClave, RepNombre, RepSuscriptor, RepCantidad, null);
        }
        
        /// <remarks/>
        public void SuscriptoresCambiosLeerImagenesAsync(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor, int RepCantidad, object userState) {
            if ((this.SuscriptoresCambiosLeerImagenesOperationCompleted == null)) {
                this.SuscriptoresCambiosLeerImagenesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuscriptoresCambiosLeerImagenesOperationCompleted);
            }
            this.InvokeAsync("SuscriptoresCambiosLeerImagenes", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre,
                        RepSuscriptor,
                        RepCantidad}, this.SuscriptoresCambiosLeerImagenesOperationCompleted, userState);
        }
        
        private void OnSuscriptoresCambiosLeerImagenesOperationCompleted(object arg) {
            if ((this.SuscriptoresCambiosLeerImagenesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuscriptoresCambiosLeerImagenesCompleted(this, new SuscriptoresCambiosLeerImagenesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuscriptoresCambiosLeer2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SuscriptoresCambiosLeer2(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor, int RepCantidad) {
            object[] results = this.Invoke("SuscriptoresCambiosLeer2", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre,
                        RepSuscriptor,
                        RepCantidad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SuscriptoresCambiosLeer2Async(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor, int RepCantidad) {
            this.SuscriptoresCambiosLeer2Async(RepCodigo, RepClave, RepNombre, RepSuscriptor, RepCantidad, null);
        }
        
        /// <remarks/>
        public void SuscriptoresCambiosLeer2Async(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor, int RepCantidad, object userState) {
            if ((this.SuscriptoresCambiosLeer2OperationCompleted == null)) {
                this.SuscriptoresCambiosLeer2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuscriptoresCambiosLeer2OperationCompleted);
            }
            this.InvokeAsync("SuscriptoresCambiosLeer2", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre,
                        RepSuscriptor,
                        RepCantidad}, this.SuscriptoresCambiosLeer2OperationCompleted, userState);
        }
        
        private void OnSuscriptoresCambiosLeer2OperationCompleted(object arg) {
            if ((this.SuscriptoresCambiosLeer2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuscriptoresCambiosLeer2Completed(this, new SuscriptoresCambiosLeer2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerArchivosCambios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerArchivosCambios(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor) {
            object[] results = this.Invoke("ObtenerArchivosCambios", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre,
                        RepSuscriptor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerArchivosCambiosAsync(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor) {
            this.ObtenerArchivosCambiosAsync(RepCodigo, RepClave, RepNombre, RepSuscriptor, null);
        }
        
        /// <remarks/>
        public void ObtenerArchivosCambiosAsync(string RepCodigo, string RepClave, string RepNombre, string RepSuscriptor, object userState) {
            if ((this.ObtenerArchivosCambiosOperationCompleted == null)) {
                this.ObtenerArchivosCambiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerArchivosCambiosOperationCompleted);
            }
            this.InvokeAsync("ObtenerArchivosCambios", new object[] {
                        RepCodigo,
                        RepClave,
                        RepNombre,
                        RepSuscriptor}, this.ObtenerArchivosCambiosOperationCompleted, userState);
        }
        
        private void OnObtenerArchivosCambiosOperationCompleted(object arg) {
            if ((this.ObtenerArchivosCambiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerArchivosCambiosCompleted(this, new ObtenerArchivosCambiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/execQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string execQuery(string RepCodigo, string RepClave, string query, bool Log) {
            object[] results = this.Invoke("execQuery", new object[] {
                        RepCodigo,
                        RepClave,
                        query,
                        Log});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void execQueryAsync(string RepCodigo, string RepClave, string query, bool Log) {
            this.execQueryAsync(RepCodigo, RepClave, query, Log, null);
        }
        
        /// <remarks/>
        public void execQueryAsync(string RepCodigo, string RepClave, string query, bool Log, object userState) {
            if ((this.execQueryOperationCompleted == null)) {
                this.execQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecQueryOperationCompleted);
            }
            this.InvokeAsync("execQuery", new object[] {
                        RepCodigo,
                        RepClave,
                        query,
                        Log}, this.execQueryOperationCompleted, userState);
        }
        
        private void OnexecQueryOperationCompleted(object arg) {
            if ((this.execQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.execQueryCompleted(this, new execQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/execQuery2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string execQuery2(string RepCodigo, string RepClave, string RepSuscriptor, string Tabla, string query) {
            object[] results = this.Invoke("execQuery2", new object[] {
                        RepCodigo,
                        RepClave,
                        RepSuscriptor,
                        Tabla,
                        query});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void execQuery2Async(string RepCodigo, string RepClave, string RepSuscriptor, string Tabla, string query) {
            this.execQuery2Async(RepCodigo, RepClave, RepSuscriptor, Tabla, query, null);
        }
        
        /// <remarks/>
        public void execQuery2Async(string RepCodigo, string RepClave, string RepSuscriptor, string Tabla, string query, object userState) {
            if ((this.execQuery2OperationCompleted == null)) {
                this.execQuery2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecQuery2OperationCompleted);
            }
            this.InvokeAsync("execQuery2", new object[] {
                        RepCodigo,
                        RepClave,
                        RepSuscriptor,
                        Tabla,
                        query}, this.execQuery2OperationCompleted, userState);
        }
        
        private void OnexecQuery2OperationCompleted(object arg) {
            if ((this.execQuery2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.execQuery2Completed(this, new execQuery2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/execQueryResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string execQueryResult(string RepCodigo, string RepClave, string query) {
            object[] results = this.Invoke("execQueryResult", new object[] {
                        RepCodigo,
                        RepClave,
                        query});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void execQueryResultAsync(string RepCodigo, string RepClave, string query) {
            this.execQueryResultAsync(RepCodigo, RepClave, query, null);
        }
        
        /// <remarks/>
        public void execQueryResultAsync(string RepCodigo, string RepClave, string query, object userState) {
            if ((this.execQueryResultOperationCompleted == null)) {
                this.execQueryResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecQueryResultOperationCompleted);
            }
            this.InvokeAsync("execQueryResult", new object[] {
                        RepCodigo,
                        RepClave,
                        query}, this.execQueryResultOperationCompleted, userState);
        }
        
        private void OnexecQueryResultOperationCompleted(object arg) {
            if ((this.execQueryResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.execQueryResultCompleted(this, new execQueryResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/execQueryInsert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string execQueryInsert(string RepCodigo, string RepClave, string RepSuscriptor, string Tabla, string query, string RowGuid) {
            object[] results = this.Invoke("execQueryInsert", new object[] {
                        RepCodigo,
                        RepClave,
                        RepSuscriptor,
                        Tabla,
                        query,
                        RowGuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void execQueryInsertAsync(string RepCodigo, string RepClave, string RepSuscriptor, string Tabla, string query, string RowGuid) {
            this.execQueryInsertAsync(RepCodigo, RepClave, RepSuscriptor, Tabla, query, RowGuid, null);
        }
        
        /// <remarks/>
        public void execQueryInsertAsync(string RepCodigo, string RepClave, string RepSuscriptor, string Tabla, string query, string RowGuid, object userState) {
            if ((this.execQueryInsertOperationCompleted == null)) {
                this.execQueryInsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecQueryInsertOperationCompleted);
            }
            this.InvokeAsync("execQueryInsert", new object[] {
                        RepCodigo,
                        RepClave,
                        RepSuscriptor,
                        Tabla,
                        query,
                        RowGuid}, this.execQueryInsertOperationCompleted, userState);
        }
        
        private void OnexecQueryInsertOperationCompleted(object arg) {
            if ((this.execQueryInsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.execQueryInsertCompleted(this, new execQueryInsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExecuteQuery(string RepCodigo, string RepClave, string RepSuscriptor, string JsonScript) {
            object[] results = this.Invoke("ExecuteQuery", new object[] {
                        RepCodigo,
                        RepClave,
                        RepSuscriptor,
                        JsonScript});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteQueryAsync(string RepCodigo, string RepClave, string RepSuscriptor, string JsonScript) {
            this.ExecuteQueryAsync(RepCodigo, RepClave, RepSuscriptor, JsonScript, null);
        }
        
        /// <remarks/>
        public void ExecuteQueryAsync(string RepCodigo, string RepClave, string RepSuscriptor, string JsonScript, object userState) {
            if ((this.ExecuteQueryOperationCompleted == null)) {
                this.ExecuteQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteQueryOperationCompleted);
            }
            this.InvokeAsync("ExecuteQuery", new object[] {
                        RepCodigo,
                        RepClave,
                        RepSuscriptor,
                        JsonScript}, this.ExecuteQueryOperationCompleted, userState);
        }
        
        private void OnExecuteQueryOperationCompleted(object arg) {
            if ((this.ExecuteQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteQueryCompleted(this, new ExecuteQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PresupuestosCombosJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PresupuestosCombosJSON(string RepCodigo, string RepClave, int Tipo) {
            object[] results = this.Invoke("PresupuestosCombosJSON", new object[] {
                        RepCodigo,
                        RepClave,
                        Tipo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PresupuestosCombosJSONAsync(string RepCodigo, string RepClave, int Tipo) {
            this.PresupuestosCombosJSONAsync(RepCodigo, RepClave, Tipo, null);
        }
        
        /// <remarks/>
        public void PresupuestosCombosJSONAsync(string RepCodigo, string RepClave, int Tipo, object userState) {
            if ((this.PresupuestosCombosJSONOperationCompleted == null)) {
                this.PresupuestosCombosJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPresupuestosCombosJSONOperationCompleted);
            }
            this.InvokeAsync("PresupuestosCombosJSON", new object[] {
                        RepCodigo,
                        RepClave,
                        Tipo}, this.PresupuestosCombosJSONOperationCompleted, userState);
        }
        
        private void OnPresupuestosCombosJSONOperationCompleted(object arg) {
            if ((this.PresupuestosCombosJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PresupuestosCombosJSONCompleted(this, new PresupuestosCombosJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveBackup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveBackup(int RepID, string RepSuscriptor, string UsuInicioSesion, string RepBaseDatos) {
            object[] results = this.Invoke("SaveBackup", new object[] {
                        RepID,
                        RepSuscriptor,
                        UsuInicioSesion,
                        RepBaseDatos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveBackupAsync(int RepID, string RepSuscriptor, string UsuInicioSesion, string RepBaseDatos) {
            this.SaveBackupAsync(RepID, RepSuscriptor, UsuInicioSesion, RepBaseDatos, null);
        }
        
        /// <remarks/>
        public void SaveBackupAsync(int RepID, string RepSuscriptor, string UsuInicioSesion, string RepBaseDatos, object userState) {
            if ((this.SaveBackupOperationCompleted == null)) {
                this.SaveBackupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveBackupOperationCompleted);
            }
            this.InvokeAsync("SaveBackup", new object[] {
                        RepID,
                        RepSuscriptor,
                        UsuInicioSesion,
                        RepBaseDatos}, this.SaveBackupOperationCompleted, userState);
        }
        
        private void OnSaveBackupOperationCompleted(object arg) {
            if ((this.SaveBackupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveBackupCompleted(this, new SaveBackupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PresupuestosCargarOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PresupuestosCargarOnline(string RepCodigo, int CliID, string RepClave, string PreTipo, int PreAnio, int PreMes) {
            object[] results = this.Invoke("PresupuestosCargarOnline", new object[] {
                        RepCodigo,
                        CliID,
                        RepClave,
                        PreTipo,
                        PreAnio,
                        PreMes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PresupuestosCargarOnlineAsync(string RepCodigo, int CliID, string RepClave, string PreTipo, int PreAnio, int PreMes) {
            this.PresupuestosCargarOnlineAsync(RepCodigo, CliID, RepClave, PreTipo, PreAnio, PreMes, null);
        }
        
        /// <remarks/>
        public void PresupuestosCargarOnlineAsync(string RepCodigo, int CliID, string RepClave, string PreTipo, int PreAnio, int PreMes, object userState) {
            if ((this.PresupuestosCargarOnlineOperationCompleted == null)) {
                this.PresupuestosCargarOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPresupuestosCargarOnlineOperationCompleted);
            }
            this.InvokeAsync("PresupuestosCargarOnline", new object[] {
                        RepCodigo,
                        CliID,
                        RepClave,
                        PreTipo,
                        PreAnio,
                        PreMes}, this.PresupuestosCargarOnlineOperationCompleted, userState);
        }
        
        private void OnPresupuestosCargarOnlineOperationCompleted(object arg) {
            if ((this.PresupuestosCargarOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PresupuestosCargarOnlineCompleted(this, new PresupuestosCargarOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecQueryWithResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExecQueryWithResult(string RepCodigo, string RepClave, string Query) {
            object[] results = this.Invoke("ExecQueryWithResult", new object[] {
                        RepCodigo,
                        RepClave,
                        Query});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExecQueryWithResultAsync(string RepCodigo, string RepClave, string Query) {
            this.ExecQueryWithResultAsync(RepCodigo, RepClave, Query, null);
        }
        
        /// <remarks/>
        public void ExecQueryWithResultAsync(string RepCodigo, string RepClave, string Query, object userState) {
            if ((this.ExecQueryWithResultOperationCompleted == null)) {
                this.ExecQueryWithResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecQueryWithResultOperationCompleted);
            }
            this.InvokeAsync("ExecQueryWithResult", new object[] {
                        RepCodigo,
                        RepClave,
                        Query}, this.ExecQueryWithResultOperationCompleted, userState);
        }
        
        private void OnExecQueryWithResultOperationCompleted(object arg) {
            if ((this.ExecQueryWithResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecQueryWithResultCompleted(this, new ExecQueryWithResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RepresentantesParametrosActualizar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RepresentantesParametrosActualizar(string RepCodigo, string RepClave, string ParReferencia, string ParValor) {
            object[] results = this.Invoke("RepresentantesParametrosActualizar", new object[] {
                        RepCodigo,
                        RepClave,
                        ParReferencia,
                        ParValor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RepresentantesParametrosActualizarAsync(string RepCodigo, string RepClave, string ParReferencia, string ParValor) {
            this.RepresentantesParametrosActualizarAsync(RepCodigo, RepClave, ParReferencia, ParValor, null);
        }
        
        /// <remarks/>
        public void RepresentantesParametrosActualizarAsync(string RepCodigo, string RepClave, string ParReferencia, string ParValor, object userState) {
            if ((this.RepresentantesParametrosActualizarOperationCompleted == null)) {
                this.RepresentantesParametrosActualizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRepresentantesParametrosActualizarOperationCompleted);
            }
            this.InvokeAsync("RepresentantesParametrosActualizar", new object[] {
                        RepCodigo,
                        RepClave,
                        ParReferencia,
                        ParValor}, this.RepresentantesParametrosActualizarOperationCompleted, userState);
        }
        
        private void OnRepresentantesParametrosActualizarOperationCompleted(object arg) {
            if ((this.RepresentantesParametrosActualizarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RepresentantesParametrosActualizarCompleted(this, new RepresentantesParametrosActualizarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargarEmpresaSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public _EmpresasC[] CargarEmpresaSync(string RepCodigo, string RepClave, string Fecha) {
            object[] results = this.Invoke("CargarEmpresaSync", new object[] {
                        RepCodigo,
                        RepClave,
                        Fecha});
            return ((_EmpresasC[])(results[0]));
        }
        
        /// <remarks/>
        public void CargarEmpresaSyncAsync(string RepCodigo, string RepClave, string Fecha) {
            this.CargarEmpresaSyncAsync(RepCodigo, RepClave, Fecha, null);
        }
        
        /// <remarks/>
        public void CargarEmpresaSyncAsync(string RepCodigo, string RepClave, string Fecha, object userState) {
            if ((this.CargarEmpresaSyncOperationCompleted == null)) {
                this.CargarEmpresaSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarEmpresaSyncOperationCompleted);
            }
            this.InvokeAsync("CargarEmpresaSync", new object[] {
                        RepCodigo,
                        RepClave,
                        Fecha}, this.CargarEmpresaSyncOperationCompleted, userState);
        }
        
        private void OnCargarEmpresaSyncOperationCompleted(object arg) {
            if ((this.CargarEmpresaSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarEmpresaSyncCompleted(this, new CargarEmpresaSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Version", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Version() {
            object[] results = this.Invoke("Version", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionAsync() {
            this.VersionAsync(null);
        }
        
        /// <remarks/>
        public void VersionAsync(object userState) {
            if ((this.VersionOperationCompleted == null)) {
                this.VersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionOperationCompleted);
            }
            this.InvokeAsync("Version", new object[0], this.VersionOperationCompleted, userState);
        }
        
        private void OnVersionOperationCompleted(object arg) {
            if ((this.VersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionCompleted(this, new VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class _PedDetalle {
        
        private string proCodigoField;
        
        private int pedCantidadField;
        
        private int pedPrecioField;
        
        /// <remarks/>
        public string ProCodigo {
            get {
                return this.proCodigoField;
            }
            set {
                this.proCodigoField = value;
            }
        }
        
        /// <remarks/>
        public int PedCantidad {
            get {
                return this.pedCantidadField;
            }
            set {
                this.pedCantidadField = value;
            }
        }
        
        /// <remarks/>
        public int PedPrecio {
            get {
                return this.pedPrecioField;
            }
            set {
                this.pedPrecioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class _EmpresasC {
        
        private int empIDField;
        
        private string empNombreField;
        
        private string empDireccionField;
        
        private string empDireccion2Field;
        
        private string empDireccion3Field;
        
        private string empRNCField;
        
        private string empTelefonoField;
        
        private string empFaxField;
        
        private byte[] empLogoField;
        
        private System.DateTime fechaUltimaActualizacionField;
        
        private string orvCodigoField;
        
        private string ofvCodigoField;
        
        private string socCodigoField;
        
        private System.DateTime empFechaActualizacionField;
        
        /// <remarks/>
        public int EmpID {
            get {
                return this.empIDField;
            }
            set {
                this.empIDField = value;
            }
        }
        
        /// <remarks/>
        public string EmpNombre {
            get {
                return this.empNombreField;
            }
            set {
                this.empNombreField = value;
            }
        }
        
        /// <remarks/>
        public string EmpDireccion {
            get {
                return this.empDireccionField;
            }
            set {
                this.empDireccionField = value;
            }
        }
        
        /// <remarks/>
        public string EmpDireccion2 {
            get {
                return this.empDireccion2Field;
            }
            set {
                this.empDireccion2Field = value;
            }
        }
        
        /// <remarks/>
        public string EmpDireccion3 {
            get {
                return this.empDireccion3Field;
            }
            set {
                this.empDireccion3Field = value;
            }
        }
        
        /// <remarks/>
        public string EmpRNC {
            get {
                return this.empRNCField;
            }
            set {
                this.empRNCField = value;
            }
        }
        
        /// <remarks/>
        public string EmpTelefono {
            get {
                return this.empTelefonoField;
            }
            set {
                this.empTelefonoField = value;
            }
        }
        
        /// <remarks/>
        public string EmpFax {
            get {
                return this.empFaxField;
            }
            set {
                this.empFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] EmpLogo {
            get {
                return this.empLogoField;
            }
            set {
                this.empLogoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaUltimaActualizacion {
            get {
                return this.fechaUltimaActualizacionField;
            }
            set {
                this.fechaUltimaActualizacionField = value;
            }
        }
        
        /// <remarks/>
        public string OrvCodigo {
            get {
                return this.orvCodigoField;
            }
            set {
                this.orvCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string OfvCodigo {
            get {
                return this.ofvCodigoField;
            }
            set {
                this.ofvCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string SocCodigo {
            get {
                return this.socCodigoField;
            }
            set {
                this.socCodigoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime empFechaActualizacion {
            get {
                return this.empFechaActualizacionField;
            }
            set {
                this.empFechaActualizacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetVersionCompletedEventHandler(object sender, GetVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PedidosCrearCompletedEventHandler(object sender, PedidosCrearCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PedidosCrearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PedidosCrearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PedidosCrear2CompletedEventHandler(object sender, PedidosCrear2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PedidosCrear2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PedidosCrear2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SuscriptoresCrearCompletedEventHandler(object sender, SuscriptoresCrearCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuscriptoresCrearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuscriptoresCrearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void VerificarSuscriptorCompletedEventHandler(object sender, VerificarSuscriptorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarSuscriptorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarSuscriptorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SuscriptoresCambiosCantidadCompletedEventHandler(object sender, SuscriptoresCambiosCantidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuscriptoresCambiosCantidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuscriptoresCambiosCantidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReplicacionesTablasLeerCompletedEventHandler(object sender, ReplicacionesTablasLeerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReplicacionesTablasLeerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReplicacionesTablasLeerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SuscriptoresCambiosLeerCompletedEventHandler(object sender, SuscriptoresCambiosLeerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuscriptoresCambiosLeerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuscriptoresCambiosLeerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SuscriptoresCambiosLeerImagenesCompletedEventHandler(object sender, SuscriptoresCambiosLeerImagenesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuscriptoresCambiosLeerImagenesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuscriptoresCambiosLeerImagenesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SuscriptoresCambiosLeer2CompletedEventHandler(object sender, SuscriptoresCambiosLeer2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuscriptoresCambiosLeer2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuscriptoresCambiosLeer2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ObtenerArchivosCambiosCompletedEventHandler(object sender, ObtenerArchivosCambiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerArchivosCambiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerArchivosCambiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void execQueryCompletedEventHandler(object sender, execQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class execQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal execQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void execQuery2CompletedEventHandler(object sender, execQuery2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class execQuery2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal execQuery2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void execQueryResultCompletedEventHandler(object sender, execQueryResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class execQueryResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal execQueryResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void execQueryInsertCompletedEventHandler(object sender, execQueryInsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class execQueryInsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal execQueryInsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ExecuteQueryCompletedEventHandler(object sender, ExecuteQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PresupuestosCombosJSONCompletedEventHandler(object sender, PresupuestosCombosJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PresupuestosCombosJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PresupuestosCombosJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SaveBackupCompletedEventHandler(object sender, SaveBackupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveBackupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveBackupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PresupuestosCargarOnlineCompletedEventHandler(object sender, PresupuestosCargarOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PresupuestosCargarOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PresupuestosCargarOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ExecQueryWithResultCompletedEventHandler(object sender, ExecQueryWithResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecQueryWithResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecQueryWithResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RepresentantesParametrosActualizarCompletedEventHandler(object sender, RepresentantesParametrosActualizarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RepresentantesParametrosActualizarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RepresentantesParametrosActualizarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CargarEmpresaSyncCompletedEventHandler(object sender, CargarEmpresaSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarEmpresaSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarEmpresaSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _EmpresasC[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_EmpresasC[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void VersionCompletedEventHandler(object sender, VersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591